# Generated by Django 2.1.7 on 2019-10-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('authors', models.CharField(max_length=120)),
                ('date', models.DateField(blank=True)),
                ('industry', models.CharField(max_length=240)),
                ('pages', models.IntegerField(max_length=120)),
                ('link', models.CharField(max_length=1024)),
                ('language', models.CharField(max_length=64)),
            ],
        ),
    ]
