# Generated by Django 2.1.7 on 2019-11-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20191031_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='industry_id_1',
            new_name='industryIdentifiers',
        ),
        migrations.RemoveField(
            model_name='book',
            name='industry_id_2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='industry_type_1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='industry_type_2',
        ),
    ]
