# Generated by Django 2.1.7 on 2020-04-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20191108_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='industryIdentifiers',
        ),
    ]
