# Generated by Django 2.1.7 on 2019-10-31 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20191030_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='industry',
            new_name='industry_id_1',
        ),
        migrations.AddField(
            model_name='book',
            name='industry_id_2',
            field=models.CharField(default=0, max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='industry_type_1',
            field=models.CharField(default=django.utils.timezone.now, max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='industry_type_2',
            field=models.CharField(default=0, max_length=240),
            preserve_default=False,
        ),
    ]
