# Generated by Django 2.1.7 on 2020-06-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200608_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.CharField(max_length=1024),
        ),
    ]
