# Generated by Django 2.1.7 on 2019-04-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='pressure',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
